modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/McMelonTV/ServerSideAdditions"
license = "MIT"

[[mods]]
modId = "serversideadditions"
version = "${version}"
displayName = "ServerSideAdditions"
authors = "mel (https://github.com/McMelonTV)"
description = '''
A set of server-side quality of life and utility additions.
'''
#logoFile = ""

[[dependencies.serversideadditions]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.serversideadditions]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.serversideadditions]]
modId = "architectury"
type = "required"
versionRange = "[17.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "serversideadditions.mixins.json"
